services:
  backend:
    image: ${ECR_REGISTRY}/issue-tracker-backend:latest
    ports:
      - "9092:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_OPTS=-Xms128m -Xmx256m
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    mem_limit: 350m
    depends_on:
      - redis

  frontend:
    image: ${ECR_REGISTRY}/issue-tracker-frontend:latest
    ports:
      - "80:80"
    mem_limit: 100m
    depends_on:
      - backend

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    mem_limit: 150m

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=1d'
    mem_limit: 150m
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    mem_limit: 200m
    depends_on:
      - prometheus
