pipeline {
    agent any

    environment {
        BACKEND_IMAGE = "issue-tracker-backend"
        DB_PASSWORD = credentials('db-password')
        MAIL_PASSWORD = credentials('mail-password')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend: Build & Test') {
            steps {
                sh './mvnw clean package'
            }
            post {
                success {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                    junit testResults: 'target/surefire-reports/*.xml', allowEmptyResults: true
                }
            }
        }

        stage('Backend: Docker Build') {
            steps {
                sh "docker build -t ${BACKEND_IMAGE}:${env.BUILD_NUMBER} ."
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop backend || true
                docker rm backend || true

                docker run -d -p 8080:8080 \
                -e DB_PASSWORD=$DB_PASSWORD \
                -e MAIL_PASSWORD=$MAIL_PASSWORD \
                --name backend ${BACKEND_IMAGE}:${BUILD_NUMBER}
                '''
            }
        }
    }

    post {
        success {
            echo 'Backend build and deployment successful!'
        }
        failure {
            echo 'Backend build or deployment failed.'
        }
    }
}

